# Spécifiez le nom de l'utilisateur qui exécutera nginx pour limiter les risques de sécurité
# user www-data;

# Spécifiez le nombre de processus nginx qui seront lancés
worker_processes auto;

# Spécifiez le chemin des fichiers de journalisation des erreurs
error_log /var/log/nginx/error.log;

# Spécifiez le chemin contenant le PID (Process ID) de nginx
pid /run/nginx.pid;

events {
	# Nombre maximum de connexions simultanées
	worker_connections 1024;
	# Accepter plusieurs connexions en même temps
	# multi_accept on;
}

http {
	##
	# Paramètres de base
	##
	# Temps d'attente maximum pour recevoir les données envoyées par le client
	# Envoyer les fichiers statiques (images, css, js) directement au client plutôt que de les faire passer par nginx
	sendfile on;
	# Format de journalisation
	log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
					  '$status $body_bytes_sent "$http_referer" '
					  '"$http_user_agent" "$http_x_forwarded_for"';
	# Emplacement des journaux d'accès
	access_log  /var/log/nginx/access.log  main;

	##
	# Paramètres des hôtes virtuels (sous-domaines)
	##
	include conf.d/*.conf;
	
	##
	# Paramètres des fichiers
	##
	# Définir les types de fichiers connus par nginx
	include /etc/nginx/mime.types;
	# Définir le type de fichier par défaut
	default_type application/octet-stream;
	# Nombre maximum de types de fichiers gérables par nginx
	types_hash_max_size 2048;

	##
	# Paramètres réseau
	##
	# Envoyer les en-têtes HTTP en une seule fois
	tcp_nopush on;
	# Désactiver la mise en mémoire tampon des données envoyées au client (envoi immédiat sans attendre que le tampon se remplisse)
	tcp_nodelay on;
	# Temps d'attente maximum pour recevoir les données envoyées par le client
	keepalive_timeout 65;

	##
	# Paramètres Gzip (compression des fichiers envoyés au client)
	##
	gzip on;
	gzip_disable "msie6";

}
