# NOTE : Docker ne peut pas récupérer des fichiers en dehors du contexte de build
# Par conséquent, nous construisons cette image à partir du répertoire racine du projet

# Image de base
FROM nginx:stable-alpine

# Définir le répertoire de travail
WORKDIR /var/www/html/

# Nginx sert les fichiers statiques et donne accès aux fichiers PHP,
# il doit donc contenir les assets ainsi que le point d'entrée de l'application
# pour rediriger les requêtes vers PHP-FPM qui renverra le contenu statique généré
COPY app/public ./public/

# Copier la configuration initiale de Nginx
COPY .docker/nginx/conf/nginx.conf /etc/nginx/nginx.conf
# Copier le modèle de configuration du site
COPY .docker/nginx/conf/conf.d/default.conf.template /etc/nginx/conf.d/default.conf.template

# Rendre l'application accessible sur le port 8000
EXPOSE 8000

# Exécuter Nginx après avoir remplacé les variables d'environnement dans le fichier de configuration
CMD ["/bin/sh", "-c", "envsubst '${PHP_SERVICE_HOST},${PHP_SERVICE_PORT}' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]